config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :articles
  resources :journals#, only: [:show, index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books#, only: [:show, :index, :new, :create]

 
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'welcome', to: 'pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
   validates :title, presence: true, length: {minimum: 5, maximum: 100}
   validates  :description, presence: true, length: {minimum: 10, maximum: 500}

end

app/models/journal.rb
class Journal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show

  # @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    #before_action :set_book, only: %i[ show edit update destroy ]
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    public
    
    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description)
    end


    def index
        @books = Book.all

    end

    def show
        #byebug
        #@book = Book.find(params[:id])
        # moved to the set_book method 
    end

    def new
        @book = Book.new 
    end

    def edit
    
    end

    def create 
        @book = Book.new(params.require(:book).permit(:title, :description))
       # render plain: params[:book]
        if  @book.save
            flash[:notice] = "The book entry was created and saved successfully."
            redirect_to book_path(@book)
            #redirect_to @book # In sortcut
        else
            render 'new'
      end
        
       
    end

    def update 
        
        if @book.update(params.require(:book).permit(:title, :description))
            flash[:notice] = "The book entry was updated successfully."
            redirect_to book_path(@book)
        else
          render 'edit'
        end
        
    end

    def destroy
        @book.destroy
        redirect_to @book
    end



end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]

  # GET /journals or /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1 or /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals or /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: "Journal was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1 or /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: "Journal was successfully updated." }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1 or /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: "Journal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:name, :fields)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end

    def contact
    end

    def home
    end

    def journals
    end

    def welcome
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/books/_form.html.erb
<%  if @book.errors.any?  %>
<% @book.errors.full_messages.each do |msg|  %>
<li> <%= msg %>   </li>


<% end %>
</ul>
<% end %>

<%= form_with(model: @book, local: true) do |f| %>
  <p> 
    <%= f.label :title %><br/> 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/> 
    <%= f.text_area :description %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Editing a new book item </h1>
<h2>The following errors prevented the book info to be saved. </h2>
<ul>

<%= render 'form', book: @book %>


<%= link_to 'Back to Book Listing page', books_path %>

app/views/books/index.html.erb
<h1>Indexing books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
      
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
        <td><%= link_to 'Delete', book_path(book.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>


<%= link_to 'New Book', new_book_path %> |
<%= link_to 'Refresh this page', books_path %> 

</p>

app/views/books/new.html.erb
<h1>Creating a new book item </h1>

<%= render 'form', book: @book %>

  
<%= link_to 'Back to listing page', books_path %> 

app/views/books/show.html.erb
<h1> Showing Book Details </h1>
<p> 
  <strong> Title: </strong> <%= @book.title %>  
</p>

<p> 
  <strong> Description: </strong> <%= @book.description %>  
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: "Are you sure to delete?" } %> |
<%= link_to 'Return to books listing', books_path %> 

app/views/journals/_form.html.erb
<%= form_with(model: journal) do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
        <% journal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :fields %>
    <%= form.text_area :fields %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journals</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fields</th>
      <th colspan="3"></th>
    
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.name %></td>
        <td><%= journal.fields %></td>
        <td><%= link_to 'Show', journal %></td>
        <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
        <td><%= link_to 'Delete', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal', new_journal_path %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @journal.name %>
</p>

<p>
  <strong>Fields:</strong>
  <%= @journal.fields %>
</p>

<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Icterguru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">ICTER Guru Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#about">About</a>
              <a class="dropdown-item" href="#contact">Contact</a>
              
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<br><br><br><br><br>

<H1> About <b> ICTER Guru </b> .... </H1>

<br>
<p>

<h1>
<%= link_to 'Articles', articles_path %> |

<%= link_to 'Books', books_path %> |

<%= link_to 'Journals', journals_path %> |

<%= link_to 'About', about_path %> |

<%= link_to 'Contact', contact_path %> |

<%= link_to 'Welcome', welcome_path %> 

</h1>

</p>

app/views/pages/contact.html.erb
<br><br>

<H1> Please email us at: <b> icterguru@gmail.com </b>. <br><br><br> Thank you! </H1>


<br>
<p>

<h1>
<%= link_to 'Articles', articles_path %> |

<%= link_to 'Books', books_path %> |

<%= link_to 'Journals', journals_path %> |

<%= link_to 'About', about_path %> |

<%= link_to 'Contact', contact_path %> |

<%= link_to 'Welcome', welcome_path %> 

</h1>

</p>

app/views/pages/home.html.erb
<br>

<H1> <b> Welcome to the <a href="https://icterguru.herokuapp.com/">ICTER Guru</a>
Online Forum </b> </H1>



<br>
আইসিটিইআর গুরু (ICTER Guru) অনলাইন ফোরামে আপনাকে স্বাগতম!
<br>
ICTER (Information and Communication Technology in Education and Research) Guru
<br>
আইসিটিইআর গুরু – শিক্ষা এবং গবেষণায় তথ্য ও যোগাযোগ প্রযুক্তি ব্যবহারের একটি অনলাইন ফোরাম
<br>
Software Development, QA Testing ম্যানুয়াল এবং অটোমেশন টেস্টিং ট্রেনিং (একটি ইন্টিগ্রেটেড অনলাইন & F2F কোর্স) এর জন্য যোগাযোগ করুন

<br>
Please contact for QA Manual & Automation Testing Training (An Integrated Online & F2F Course)  Training

<br>
বিস্তারিত তথ্যের জন্য যোগাযোগ করুন:
<br>
Email: icterguru@gmail.com, info@icterguru.com
<br>
Web: https://icterguru.com
<br>
Facebook: facebook.com/icterGuru
<br>
YouTube Channel: youtube.com/icterGuru
<br>
পরিচালনায়:
<br>
ICTER Guru – আইসিটিইআর গুরু – শিক্ষা এবং গবেষণায় তথ্য ও যোগাযোগ প্রযুক্তি ব্যবহারের একটি অনলাইন ফোরাম
<br>
Welcome to the Information and Communication Technology in Education and Research (ICTER) Guru Online Forum.
<br>
In this page, we discuss our plan, procedures, and implementation of Effective usages and practices of using  Information and Communication Technology in Education and Research (ICTER) purposes.
<br>
Have questions, comments, or suggestion? Please let us know.
<br>
Thank you so much!
<br>
ICTERGuru Administrator.

<br>

<h1> <b> <br>  <a href="https://icterguru.herokuapp.com/"> Production Home Page</a> </b> </h1>
<h1> <b> <br>  <a href="https://icterguru.herokuapp.com/contact"> Production Contact Page</a> </b> </h1>
<h1> <b> <br>  <a href="https://icterguru.herokuapp.com/articles"> Production Articles Page</a> </b> </h1>
<h1> <b> <br>  <a href="https://icterguru.herokuapp.com/journals"> Production Journals Page</a> </b> </h1>

<br>
<p>

<h1>
<%= link_to 'Articles', articles_path %> |

<%= link_to 'Books', books_path %> |

<%= link_to 'Journals', journals_path %> |

<%= link_to 'About', about_path %> |

<%= link_to 'Contact', contact_path %> |

<%= link_to 'Welcome', welcome_path %> 

</h1>

</p>

app/views/pages/members.html.erb
<br>
<p>

<h1>
<%= link_to 'Articles', articles_path %> |

<%= link_to 'Books', books_path %> |

<%= link_to 'Journals', journals_path %> |

<%= link_to 'About', about_path %> |

<%= link_to 'Contact', contact_path %> |

<%= link_to 'Welcome', welcome_path %> 

</h1>

</p>

app/views/pages/welcome.html.erb
<br><br><br><br><br>

<H1>Welcome to the <b> ICTER Guru </b> Online Forum </H1>

<br>
<p>

<h1>
<%= link_to 'Articles', articles_path %> |

<%= link_to 'Books', books_path %> |

<%= link_to 'Journals', journals_path %> |

<%= link_to 'About', about_path %> |

<%= link_to 'Contact', contact_path %> |

<%= link_to 'Welcome', welcome_path %> 

</h1>

</p>